### ISSUE TITLE
BetterInvites causes crashes

### ISSUE THREAD

**Issue by Annabxlla** [RobinRMC/VencordPlus#55]
### Discord Username

Annabxlla

### What happens when the bug or crash occurs?

After the latest update and enabling BetterInvites loading the channel 269519917693272074, in the Rainbow 6 discord server (discord.gg/rainbow6) causes discord to crash, sending the user back to the @me channel.

### What is the expected behaviour?

I expect discord to load the channel like all the other channels.

### How do you recreate this bug or crash?

1. Enable BetterInvites
2. Navigate to https://discord.com/channels/253581140072464384/269519917693272074 (in discord.gg/rainbow6)
3. Observe crash

### Errors

```
TypeError: Cannot read properties of undefined (reading 'Plugins')
    at g (WebpackModule680668:2:1331)
    at ap (web.8015fd8….js:12:995051)
    at l (web.8015fd8….js:12:1052735)
    at oU (web.8015fd8….js:12:1035730)
    at web.8015fd8….js:12:1035596
    at ok (web.8015fd8….js:12:1035604)
    at oA (web.8015fd8….js:12:1032355)
    at oR (web.8015fd8….js:12:1032744)
    at r6 (web.8015fd8….js:12:981415)
    at oD (web.8015fd8….js:12:1033193)
a9	@	web.8015fd8….js:12
a.componentDidCatch.n.callback	@	web.8015fd8….js:12
iJ	@	web.8015fd8….js:12
sX	@	web.8015fd8….js:12
e	@	web.8015fd8….js:12
(anonymous)	@	web.8015fd8….js:12
oB	@	web.8015fd8….js:12
oR	@	web.8015fd8….js:12
r6	@	web.8015fd8….js:12
oD	@	web.8015fd8….js:12
t.flushSync	@	web.8015fd8….js:12
toggleShow	@	web.8015fd8….js:12
hide	@	web.8015fd8….js:12
(anonymous)	@	web.8015fd8….js:12
eG	@	web.8015fd8….js:12
eH	@	web.8015fd8….js:12
(anonymous)	@	web.8015fd8….js:12
re	@	web.8015fd8….js:12
rt	@	web.8015fd8….js:12
(anonymous)	@	web.8015fd8….js:12
oO	@	web.8015fd8….js:12
eM	@	web.8015fd8….js:12
ro	@	web.8015fd8….js:12
tG	@	web.8015fd8….js:12
tk	@	web.8015fd8….js:12
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by RobinRMC** [comment]
I'll look into this later today.

**Comment by RobinRMC** [comment]
I have confirmed this issue, but am unable to fix it, because of my lack of programming skills. We'll have to wait for an update.

**Comment by RobinRMC** [comment]
The issue has been fixed with commit 264ff619b485aba006c5d8f167515b665fa96e38. It was caused due to a mistake by me.
